// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: sandboxing.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The get funds request message
type GetFundsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount float32 `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *GetFundsRequest) Reset() {
	*x = GetFundsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sandboxing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundsRequest) ProtoMessage() {}

func (x *GetFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundsRequest.ProtoReflect.Descriptor instead.
func (*GetFundsRequest) Descriptor() ([]byte, []int) {
	return file_sandboxing_proto_rawDescGZIP(), []int{0}
}

func (x *GetFundsRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetFundsRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// The get funds response message
type GetFundsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *GetFundsResponse) Reset() {
	*x = GetFundsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sandboxing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundsResponse) ProtoMessage() {}

func (x *GetFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundsResponse.ProtoReflect.Descriptor instead.
func (*GetFundsResponse) Descriptor() ([]byte, []int) {
	return file_sandboxing_proto_rawDescGZIP(), []int{1}
}

func (x *GetFundsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_sandboxing_proto protoreflect.FileDescriptor

var file_sandboxing_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x39, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x64, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2c, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x3c, 0x0a, 0x07, 0x53,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x12, 0x31, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6e,
	0x64, 0x73, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x73, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_sandboxing_proto_rawDescOnce sync.Once
	file_sandboxing_proto_rawDescData = file_sandboxing_proto_rawDesc
)

func file_sandboxing_proto_rawDescGZIP() []byte {
	file_sandboxing_proto_rawDescOnce.Do(func() {
		file_sandboxing_proto_rawDescData = protoimpl.X.CompressGZIP(file_sandboxing_proto_rawDescData)
	})
	return file_sandboxing_proto_rawDescData
}

var file_sandboxing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sandboxing_proto_goTypes = []interface{}{
	(*GetFundsRequest)(nil),  // 0: GetFundsRequest
	(*GetFundsResponse)(nil), // 1: GetFundsResponse
}
var file_sandboxing_proto_depIdxs = []int32{
	0, // 0: Sandbox.GetFunds:input_type -> GetFundsRequest
	1, // 1: Sandbox.GetFunds:output_type -> GetFundsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sandboxing_proto_init() }
func file_sandboxing_proto_init() {
	if File_sandboxing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sandboxing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFundsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sandboxing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFundsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sandboxing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandboxing_proto_goTypes,
		DependencyIndexes: file_sandboxing_proto_depIdxs,
		MessageInfos:      file_sandboxing_proto_msgTypes,
	}.Build()
	File_sandboxing_proto = out.File
	file_sandboxing_proto_rawDesc = nil
	file_sandboxing_proto_goTypes = nil
	file_sandboxing_proto_depIdxs = nil
}
